### ISSUE TITLE
bow.py example doesn't work

### ISSUE THREAD

**Issue by sileod** [facebookresearch/SentEval#17]
Hi, I'm using Python 3.6 and  Torch 0.2.0.04
I get an error when using senteval on my own scripts so I called  bow.py and got this error
```2017-09-13 12:06:31,801 : ***** Transfer task : MRPC *****

2017-09-13 12:06:38,010 : Found 3 words with word vectors, out of         3 words
2017-09-13 12:06:38,015 : Computing embedding for train
Traceback (most recent call last):
  File "bow.py", line 80, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/senteval.py", line 62, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/senteval.py", line 62, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/senteval.py", line 104, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/mrpc.py", line 76, in run
    mrpc_embed[key][txt_type] = np.vstack(mrpc_embed[key][txt_type])
  File "/home/dsileo/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```
I think it's MRPC-specific because other tasks work

**Comment by aconneau** [comment]
Hi,

it seems like MRPC was not downloaded correctly (it only shows 3 words in the vocabulary).
Could you check manually that MRPC contains actual text?

MRPC is downloaded in a particular way (because it's a .msi file) in the ./get_transfer_data_ptb.bash : it requires a "cabextract" package that is not by default in most OS.
Please try to check if cabextract was downloaded properly and select the few lines here : https://github.com/facebookresearch/SentEval/blob/master/data/get_transfer_data_ptb.bash#L216-L242 to try and download it again.

**Comment by aconneau** [comment]
Let us know if you still have an issue. Thanks
