### ISSUE TITLE
Error when running bow.py with MRPC

### ISSUE THREAD

**Issue by ZeweiChu** [facebookresearch/SentEval#23]
When I run bow.py with MRPC task, I got the following error. Any idea why it happened? 

2017-10-27 18:33:33,375 : ***** Transfer task : MRPC *****

2017-10-27 18:33:55,791 : Found 3 words with word vectors, out of         3 words
2017-10-27 18:33:55,791 : Computing embedding for test
Traceback (most recent call last):
  File "bow.py", line 80, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/senteval.py", line 62, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/senteval.py", line 62, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/senteval.py", line 104, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/mrpc.py", line 76, in run
    mrpc_embed[key][txt_type] = np.vstack(mrpc_embed[key][txt_type])
  File "/share/data/speech/zewei/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

**Comment by ZeweiChu** [comment]
It was due to the fact that MRPC data was not downloaded...
