### ISSUE TITLE
COCO Caption Retrieval task broken under Python 3.5

### ISSUE THREAD

**Issue by cifkao** [facebookresearch/SentEval#24]
With Python 3.5.2, the Image Caption Retrieval task fails because the pickled COCO data (presumably from Python 2) cannot be loaded:

```
Traceback (most recent call last):
  File "../../scripts/nm-senteval.py", line 99, in <module>
    main()
  File "../../scripts/nm-senteval.py", line 59, in main
    results = se.eval(transfer_tasks)
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/senteval/engine.py", line 56, in eval
    self.results = {x: self.eval(x) for x in name}
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/senteval/engine.py", line 56, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/senteval/engine.py", line 89, in eval
    self.evaluation = ImageCaptionRetrievalEval(tpath + '/COCO', seed=self.params.seed)
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/senteval/rank.py", line 31, in __init__
    train, dev, test = self.loadFile(task_path)
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/senteval/rank.py", line 47, in loadFile
    cocodata = pickle.load(f)
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by aconneau** [comment]
Hi, I was able to reproduce your issue. I fixed it by changing these two lines:

```python
with open(os.path.join(fpath, split + '.pkl')) as f:
    cocodata = pickle.load(f)
```
here : https://github.com/facebookresearch/SentEval/blob/master/senteval/rank.py#L46-L47

to:
```python
with open(os.path.join(fpath, split + '.pkl'), 'rb') as f:
    cocodata = pickle.load(f, encoding='latin1')
```

**Comment by cifkao** [comment]
Hi, thank you. That seems to do the trick.
