### ISSUE TITLE
The code compatability with latest pytorch 0.4

### ISSUE THREAD

**Issue by gitathrun** [facebookresearch/SentEval#30]
Just upgrade pytorch to version 0.4, and run SentEval got following errors:
```python
2018-04-26 09:47:53,927 : ***** Transfer task : CR *****


2018-04-26 09:47:54,220 : Generating sentence embeddings
2018-04-26 09:51:28,118 : Generated sentence embeddings
2018-04-26 09:51:28,118 : Training pytorch-MLP-nhid0-adam-bs64 with (inner) 10-fold cross-validation
../senteval/tools/classifier.py:108: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  all_costs.append(loss.data[0])
../senteval/tools/classifier.py:123: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  Xbatch = Variable(devX[i:i + self.batch_size], volatile=True)
../senteval/tools/classifier.py:124: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  ybatch = Variable(devy[i:i + self.batch_size], volatile=True)
2018-04-26 09:52:07,491 : Best param found at split 1: l2reg = 1e-05                 with score 0.0
Traceback (most recent call last):
  File "use_senteval.py", line 64, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 56, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 56, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 94, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/binary.py", line 57, in run
    devacc, testacc = clf.run()
  File "../senteval/tools/validation.py", line 103, in run
    self.testresults.append(round(100*clf.score(X_test, y_test), 2))
TypeError: type Tensor doesn't define __round__ method
```
Same code runs OK with pytorch 0.3 with usepytorch=True
Same code runs OK if you use sklearn intead of pytorch MLP

Not sure this round() is caused by python's native round() trick or the problem of pytorch.

Reminder: for developers who want to use SentEval framework, be caution to upgrade pytorch to version 0.4.0, especially you ware using MLP classifier of pytorch for benchmark comprarison.

**Comment by douwekiela** [comment]
Thanks for letting us know. #31 should fix this issue.
