### ISSUE TITLE
non-compatibility with InferSent

### ISSUE THREAD

**Issue by OanaMariaCamburu** [facebookresearch/SentEval#32]
Hi,

The updated version of SentEval raises errors when trying to use infersent.py to evaluate the trained infersent model.

Traceback (most recent call last):
  File "infersent.py", line 61, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 56, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 56, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 94, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/binary.py", line 47, in run
    embeddings = batcher(params, batch)
  File "infersent.py", line 38, in batcher
    tokenize=False)
  File "/raid/data/oanuru/SentEval_dld/SentEval/examples/models.py", line 200, in encode
    if self.use_cuda:
  File "/data/dgx1/oanuru/anaconda3/envs/infersent/lib/python2.7/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'BLSTMEncoder' object has no attribute 'use_cuda'

Thanks!

**Comment by OanaMariaCamburu** [comment]
Thanks, but there is still incompatibility. The model is trained model from the most recent version of InferSent.

SourceChangeWarning: source code of class 'models.BLSTMEncoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
2018-05-07 19:03:31,693 : ***** Transfer task : MR *****


Found 18489(/20327) words with glove vectors
Vocab size : 18489
2018-05-07 19:03:38,422 : Generating sentence embeddings
/raid/data/oanuru/SentEval_last/SentEval/examples/models.py:54: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  sent_output = self.enc_lstm(sent_packed)[0]  # seqlen x batch x 2*nhid
2018-05-07 19:03:47,251 : Generated sentence embeddings
2018-05-07 19:03:47,253 : Training pytorch-MLP-nhid0-adam-bs64 with (inner) 10-fold cross-validation
Traceback (most recent call last):
  File "infersent.py", line 61, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 56, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 56, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 94, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/binary.py", line 57, in run
    devacc, testacc = clf.run()
  File "../senteval/tools/validation.py", line 82, in run
    validation_data=(X_in_test, y_in_test))
  File "../senteval/tools/classifier.py", line 78, in fit
    self.trainepoch(trainX, trainy, epoch_size=self.epoch_size)
  File "../senteval/tools/classifier.py", line 108, in trainepoch
    all_costs.append(loss.data.item())
AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'item'

**Comment by aconneau** [comment]
@kahne : This seems to be linked to 0a1ecc6484556ca35e0addd89f35cfe64fc21417 for pytorch 0.4 compatibility.

**Comment by aconneau** [comment]
@OanaMariaCamburu : it seems that you're using an "old" version of pytorch. A temporary trick would consist in reverting the commit https://github.com/facebookresearch/SentEval/commit/0a1ecc6484556ca35e0addd89f35cfe64fc21417 (that is, simply modifying the two lines changed by this commit).

Since Pytorch moved to version >0.4, we modified SentEval accordingly. During this transition period where people are still using older versions of pytorch, there might some problems related to that.
Thanks

@kahne : Please mention the move to pytorch 0.4 in the README. Thanks
