### ISSUE TITLE
Probing Tasks Don't Work

### ISSUE THREAD

**Issue by ppotash** [facebookresearch/SentEval#33]
Hi,

I try to run the bow.py example with just the probing tasks (I haven't downloaded the transfer data) and I get `AssertionError: Length not in ['CR', 'MR', 'MPQA', 'SUBJ', 'SST2', 'SST5', 'TREC', 'MRPC', 'SICKRelatedness', 'SICKEntailment', 'STSBenchmark', 'SNLI', 'ImageCaptionRetrieval', 'STS12', 'STS13', 'STS14', 'STS15', 'STS16']`

Thank You,
Peter

**Comment by ppotash** [comment]
I pulled and got past the initial error, but now I'm left with 
`$ python bow.py
2018-05-15 21:52:52,819 : ***** (Probing) Transfer task : LENGTH classification *****
2018-05-15 21:52:53,256 : Loaded 99996 train - 9996 dev - 9996 test for Length
2018-05-15 21:53:03,159 : Found 36849 words with word vectors, out of         36851 words
2018-05-15 21:53:03,162 : Computing embeddings for train/dev/test
2018-05-15 21:53:11,605 : Computed embeddings
2018-05-15 21:53:11,605 : Training pytorch-MLP-nhid0-rmsprop-bs128 with standard validation..
Traceback (most recent call last):
  File "bow.py", line 66, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 59, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 59, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 121, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/probing.py", line 94, in run
    devacc, testacc = clf.run()
  File "../senteval/tools/validation.py", line 218, in run
    validation_data=(self.X['valid'], self.y['valid']))
  File "../senteval/tools/classifier.py", line 78, in fit
    self.trainepoch(trainX, trainy, epoch_size=self.epoch_size)
  File "../senteval/tools/classifier.py", line 108, in trainepoch
    all_costs.append(loss.data.item())
AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'item'`

**Comment by aconneau** [comment]
Hi, this is linked to the new pytorch version. 

You can revert the changes in https://github.com/facebookresearch/SentEval/commit/0a1ecc6484556ca35e0addd89f35cfe64fc21417 if you're still using the old pytorch version.

Thanks!

**Comment by ppotash** [comment]
Success after updating pytorch (y)
