### ISSUE TITLE
have issue when run bow.py

### ISSUE THREAD

**Issue by flyboyer** [facebookresearch/SentEval#51]
> Traceback (most recent call last):
  File "bow.py", line 111, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 59, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 59, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 121, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/binary.py", line 49, in run
    enc_input = np.vstack(enc_input)
  File "/home/zzh/wyk_paper/software/anaconda3/envs/sentEval/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

when run bow's Transfer task : MR ，it's appear this issue.how to solve it and why?

**Comment by devfoo-one** [comment]
@flyboyer I had the same issue and fixed it for me: The problem was that i accidentally deleted the `SentEval/data/downstream/tokenizer.sed` file (wrong `.gitignore` config for the data folders). This led to empty data files `SentEval/data/MR/Rt-polarity.* which caused the `enc_input = np.vstack(enc_input)` to crash because the `enc_input` was an empty list.

So checking if your `tokenizer.sed` exists and if your `Rt-polarity.*` files do contain data should help.
